Hello, world!
0123456789abcdef
entity not foundconnection resethost unreachableno storage spaceinvalid filenamestd/src/alloc.rs             at PermissionDeniedAddrNotAvailable.debug_types.dwo
/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/collections/btree/navigate.rs/rust/deps/gimli-0.29.0/src/read/line.rs
/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/str/pattern.rsreentrant init/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/cell/once.rs
/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/slice/sort/stable/quicksort.rsmid > lencalled `Result::unwrap()` on an `Err` value/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/slice.rsinternal error: entered unreachable code
/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/vec/mod.rs
/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/string.rs/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/raw_vec.rs/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/num/wrapping.rs.debug_abbrev.debug_addr.debug_aranges.debug_cu_index.debug_info.debug_line.debug_line_str.debug_loc.debug_loclists.debug_ranges.debug_rnglists.debug_str.debug_str_offsets.debug_tu_index.debug_types/rust/deps/object-0.36.5/src/read/macho/symbol.rs/rust/deps/object-0.36.5/src/read/macho/section.rs/rust/deps/object-0.36.5/src/read/macho/segment.rsInvalid archive member headerInvalid archive member size/rust/deps/object-0.36.5/src/read/archive.rsInvalid archive extended name offsetInvalid archive extended name length
Archive member size is too largeInvalid archive terminator
/rust/deps/addr2line-0.22.0/src/lib.rs/rust/deps/addr2line-0.22.0/src/function.rsfatal runtime error: initialization or cleanup bug
fatal runtime error: code running before main must not use thread::current
std/src/rt.rsfatal runtime error: drop of the panic payload panicked
use of std::thread::current() is not possible after the thread's
         local data has been destroyedstd/src/thread/current.rsfatal runtime error: 
            Attempted to access thread-local data while allocating said data.
            Do not access functions that allocate in the global allocator!
            This is a bug in the global allocator.
        
/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/iter/traits/iterator.rs
fatal runtime error: an irrecoverable error occurred while synchronizing threads
std/src/thread/mod.rsfailed to generate unique thread ID: bitspace exhausted
RUST_BACKTRACE
std/src/io/buffered/bufwriter.rsfailed to write the buffered data
std/src/io/buffered/linewritershim.rs
permission deniedconnection refusednetwork unreachableconnection abortednot connectedaddress in useaddress not availablenetwork downbroken pipeentity already existsoperation would blocknot a directoryis a directorydirectory not emptyread-only filesystem or storage mediumfilesystem loop or indirection limit (e.g. symlink loop)stale network file handleinvalid input parameterinvalid datatimed outwrite zeroseek on unseekable filefilesystem quota exceededfile too largeresource busyexecutable file busycross-device link or renametoo many linksargument list too longoperation interruptedunsupportedunexpected end of fileout of memoryin progressother erroruncategorized errorOsmessageErrorCustomerror (os error )
std/src/io/stdio.rsfailed printing to : stdout
std/src/io/mod.rs
failed to write whole buffera formatting trait implementation returned an error when the underlying stream did notpanicked at :
std/src/path.rs
std/src/sync/once.rs
lock count overflow in reentrant mutexstd/src/sync/reentrant_lock.rs
file name contained an unexpected NUL bytestack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
__rust_begin_short_backtrace__rust_end_short_backtraces      [... omitted  frame ...]
<unknown>
memory allocation of  bytes failed
 bytes failedfatal runtime error: Rust panics must be rethrown
fatal runtime error: Rust cannot catch foreign exceptions
<unnamed>' panicked at 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Box<dyn Any>aborting due to panic at 
thread panicked while processing panic. aborting.
thread caused non-unwinding panic. aborting.
fatal runtime error: failed to initiate panic, error 
std/src/../../backtrace/src/symbolize/mod.rs -       
ConnectionRefusedConnectionResetHostUnreachableNetworkUnreachableConnectionAbortedNotConnectedAddrInUseNetworkDownBrokenPipeAlreadyExistsWouldBlockNotADirectoryIsADirectoryDirectoryNotEmptyReadOnlyFilesystemFilesystemLoopStaleNetworkFileHandleInvalidInputInvalidDataWriteZeroStorageFullNotSeekableFilesystemQuotaExceededFileTooLargeResourceBusyExecutableFileBusyCrossesDevicesTooManyLinksInvalidFilenameArgumentListTooLongInterruptedUnsupportedUnexpectedEofOutOfMemoryInProgressOtherUncategorized
unexpected error during closedir: std/src/sys/pal/unix/fs.rs
strerror_r failurestd/src/sys/pal/unix/os.rs/dev/null
thread '' has overflowed its stack
fatal runtime error: stack overflow
failed to set up alternative stack guard page: std/src/sys/pal/unix/stack_overflow.rsfailed to allocate an alternative stack: failed to protect the guard page: failed to allocate a guard page: 
fatal runtime error: assertion failed: signal(libc::SIGPIPE, handler) != libc::SIG_ERR
std/src/sys/pal/unix/mod.rs
std/src/sys/sync/mutex/pthread.rsfailed to lock mutex: Once instance has previously been poisonedstd/src/sys/sync/once/queue.rsstd/src/sys/sync/rwlock/queue.rsfatal runtime error: tried to drop node in intrusive list.
failed to create dispatch semaphore for thread synchronizationstd/src/sys/sync/thread_parking/darwin.rsstd/src/sys/thread_local/destructors/list.rsfatal runtime error: the global allocator may not use TLS with destructors
cannot panic during the backtrace functionstd/src/../../backtrace/src/backtrace/libunwind.rs.debug_abbrev.dwo.debug_info.dwo.debug_line.dwo.debug_loc.dwo.debug_loclists.dwo.debug_rnglists.dwo.debug_str.dwo.debug_str_offsets.dwostd/src/../../backtrace/src/symbolize/gimli.rs
Contents/Resources/DWARFstd/src/../../backtrace/src/symbolize/gimli/macho.rs
std/src/../../backtrace/src/symbolize/gimli/libs_macos.rs
)#))")))
')))))))))))
)))))))$
deadlockthread 'NotFoundTimedOutDeadlock
maincodekindKind/
/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/char/methods.rsto_digit: invalid radix -- radix must be in the range 2 to 36 inclusive/rust/deps/object-0.36.5/src/read/archive.rs/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/slice.rs/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/string.rs/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/raw_vec.rs:\
/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/slice.rs/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/collections/btree/map/entry.rsassertion failed: idx < CAPACITY/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/alloc/src/collections/btree/node.rsassertion failed: edge.height == self.height - 1assertion failed: src.len() == dst.len()assertion failed: edge.height == self.node.height - 1
/rust/deps/gimli-0.29.0/src/read/abbrev.rs
()/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/ops/function.rs/rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/str/pattern.rscalled `Result::unwrap()` on an `Err` valueErrorEmptyInvalidDigitPosOverflowNegOverflowParseIntError
/rust/deps/rustc-demangle-0.1.24/src/legacy.rs::C,)(><&*@.
/rust/deps/rustc-demangle-0.1.24/src/v0.rs`fmt::Error`s should be impossible without a `fmt::Formatter`punycode{-}0internal error: entered unreachable codeinternal error: entered unreachable code: str::from_utf8( was expected to have 1 char, but  chars were foundstri8i16i32i64isizeu8u16u32u64usizef32f64!_...{recursion limit reached}?'> , []::{closure:# const ;  + unsafe " fn( = false{ {  }: 0x.llvm./rust/deps/rustc-demangle-0.1.24/src/lib.rs{size limit reached}`fmt::Error` from `SizeLimitedFmtAdapter` was discardedSizeLimitExhausted
{invalid syntax}extern "Zero) = boolchari128u128for<shim as mut dyn  -> truecalled `Result::unwrap()` on an `Err` valueLayoutErrorcapacity overflowalloc/src/raw_vec.rsalloc/src/string.rsalloc/src/ffi/c_str.rsalloc/src/slice.rsalloc/src/sync.rs
assertion `left  right` failed: ) when slicing `range end index  (bytes 
BorrowMutErroralready borrowed: 
called `Option::unwrap()` on a `None` value
core/src/panicking.rs
index out of bounds: the len is  but the index is 
panic in a function that cannot unwindpanic in a destructor during cleanup==!=matches right` failed
  left: 
 right: 
  left: 
:  { ,  {
} }((
00010203040506070809101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899
core/src/fmt/mod.rs
core/src/slice/memchr.rsuser-provided comparison function does not correctly implement a total ordercore/src/slice/sort/shared/smallsort.rs
attempted to index str up to maximum usizecore/src/str/mod.rs
core/src/str/pattern.rs
[...]begin <= end (`byte index  is not a char boundary; it is inside ) of ` is out of bounds of `
core/src/unicode/printable.rs
';>NO
6=>V
67VW
)14:EFIJNOde
;>fi
./'(U
:?EQ
"%>?
 #%&(38:HJLPSUVXZ\^`cefksx}
PI73
<dSH
./?\]_
)147:;=IJ]
)14:;EFIJ^de
):;EIW[\^_de
EIde
INOWY^_
FGNOXZ\^~
NOZ[
no7=?BE
%_ m
core/src/unicode/unicode_data.rs
attempt to divide by zeroattempt to calculate the remainder with a divisor of zero
range start index  out of range for slice of length slice index starts at  but ends at 
, +*0
jaTOo
     <= 
